command:
  - uvicorn
  - server.main:app
  - --host=0.0.0.0
  - --port=8000

env:
  - name: GENIE_SPACE_ID
    value: "01f17f8acc3d128e86800518c1dace5e"
  - name: DASHBOARD_ID
    value: "01f17f8a836612adbe8cb0bc36371b43"
