command:
  - uvicorn
  - server.main:app
  - --host=0.0.0.0
  - --port=8000

env:
  - name: GENIE_SPACE_ID
    value: "01f1805f4955155fa4947e73bccf6116"
  - name: DASHBOARD_ID
    value: "01f1805e2d491d3dbfa966e38b445156"
